### ISSUE TITLE
Getting error on gcteam create

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/Builder-System-Plugin#11]
Executed command: /gcteam Create test

![2022-03-31_19-47.png](https://images.zenhubusercontent.com/623226cee4e03cb5f7f2dbeb/d1971456-2b4b-4ca2-8b9e-630ace922b37)

**Comment by kevinxdev** [comment]
```
[31.03 19:44:22.763] INFO: [Lobby-1] [19:44:22 WARN]: de.dytanic.cloudnet.driver.event.EventListenerException: Error while invoking event listener handleServiceConnected in class net.gigaclub.buildersystemplugin.Commands.BuildServerCreate
[31.03 19:44:22.763] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.event.DefaultRegisteredEventListener.fireEvent(DefaultRegisteredEventListener.java:71)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.event.DefaultEventManager.fireEvent(DefaultEventManager.java:141)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.event.DefaultEventManager.fireEvent(DefaultEventManager.java:131)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.event.DefaultEventManager.callEvent(DefaultEventManager.java:118)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.event.IEventManager.callEvent(IEventManager.java:40)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.wrapper.network.listener.PacketServerServiceInfoPublisherListener.invoke0(PacketServerServiceInfoPublisherListener.java:70)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.wrapper.network.listener.PacketServerServiceInfoPublisherListener.handle(PacketServerServiceInfoPublisherListener.java:50)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:152)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.network.protocol.DefaultPacketListenerRegistry.handlePacket(DefaultPacketListenerRegistry.java:146)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.network.netty.NettyNetworkHandler.lambda$channelRead0$0(NettyNetworkHandler.java:67)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at java.base/java.lang.Thread.run(Thread.java:833)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "de.dytanic.cloudnet.ext.bridge.player.IPlayerManager.getOnlinePlayers(String)" because "this.playerManager" is null
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at buildersystemplugin-1.18.2.1.0.0-all.jar//net.gigaclub.buildersystemplugin.Commands.BuildServerCreate.handleServiceConnected(BuildServerCreate.java:43)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at GeneratedListenerInvoker_8a03d981aa304781a57f5aecece26766.invoke(GeneratedListenerInvoker_8a03d981aa304781a57f5aecece26766.java)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   at de.dytanic.cloudnet.driver.event.DefaultRegisteredEventListener.fireEvent(DefaultRegisteredEventListener.java:69)
[31.03 19:44:22.764] INFO: [Lobby-1] [19:44:22 WARN]:   ... 12 more
```
